### ISSUE TITLE
Составить таймлайн

### ISSUE THREAD

**Issue by neonila-kunyk** [neonila-kunyk/homepage#6]
Составить список всех (важных) жизненных событий, памятных дат, достижений, периодов, которые дали приятный и неприятный опыт, и т.п. В этом конкретном случае длинных списков не бывает, бывают плохо свернутые, поэтому пакуем сюда всё подряд, а про "лишние" события можно будет промолчать позже. Список должен быть систематизирован и отсортирован таким образом, чтоб читатель быстро понял "паттерн" и мог легко ориентироваться в пространстве и времени этого резюме.

**Comment by neonilakunyk** [comment]
**EDUCATION**
•	Ph.D. in Artificial Intelligence, Massachusetts Institute of Technology, 1977.  Dissertation in the M.I.T.  Artificial Intelligence Laboratory under Professor Gerald J.  Sussman: "NETL: A System for Representing and Using Real-World Knowledge".
•	M.S. in Electrical Engineering and Computer Science, Massachusetts Institute of Technology, 1973.  Master's thesis under Professor Patrick H. Winston: "A Planning System for Robot Construction Tasks".
•	B.S. in Electrical Engineering and Computer Science, Massachusetts Institute of Technology, 1973.

**EMPLOYMENT**
•	July 1978-Present:  Carnegie Mellon University. Professor Emeritus since 2017; Research Professor of Computer Science since 1994; Research Associate Professor, 1984-1994;  Research Assistant Professor 1978-1984.
•	July 2000- April 2003:  Research Staff Member, IBM T.J.Watson Research Center.  (On leave from CMU.)
•	May 1996-July 2000:  Justsystem Pittsburgh Research Center, Pittsburgh PA.  President and Chief Technical Officer.  (On partial leave from CMU.)
•	September 1977–June 1978:  N. E. Berg Company, Bedford NH.  Consultant, developing software for document production and a specialized operating system.

**HONORS**
•	Fellow of the American Association for Artificial Intelligence (AAAI).
•	2013 Outstanding Technology Contributions Award, Web Intelligence Consortium.
•	Quora Top Writer, 2016-present.

**PUBLICATIONS**
•	Sagae, A. and Fahlman, S.E. (2015) "Image Retrieval with Textual Label Similarity Features",  Intelligent Systems in Accounting, Finance, and Management 2015, pages 1-13, John Wiley & Sons.
•	Sagae, A. and Fahlman, S.E. (2013) “Knowledge Resource Development for Identifying Matching Image Descriptions.” in Proceedings of the 5th International Conference on Knowledge Engineering and Ontology Development (KEOD 2013).
•	Fahlman, S.E. (2012), “Beyond Idiot-Savant AI” in Advances in Cognitive Systems 1, pages 15-22.
•	Santofimia, M. J., S.E. Fahlman, F. Moya, and J.C. López (2011), "A semantic model for actions and events in ambient intelligence", Engineering Applications of Artificial Intelligence 24, pages 1432–1445.
•	Fahlman, S. E. (2011), “Using Scone’s multiple-context mechanism to emulate human-like reasoning”, Proceedings of the AAAI Fall Symposium on Advances in Cognitive Systems.
•	Santofimia, M. J., S.E. Fahlman, F. Moya, and J.C. López (2010), “A Common-Sense Planning Strategy for Ambient Intelligence”, 14th International Conference on Knowledge-Based and Intelligent Information and Engineering Systems (KES 2010), Cardiff, Wales, UK.
•	Shultz, T.R. and S.E. Fahlman, S.E. (2010), “Cascade-Correlation”, chapter in Encyclopedia of Machine Learning, C. Sammut and G. Webb (eds.), Springer-Verlag.
•	Tribble, A. and S.E. Fahlman (2007),  "CMU-AT: Semantic Distance and Background Knowledge for Identifying Semantic Relations" Proceedings of SemEval-2007: 4th International Workshop on Semantic Evaluations. Prague, Czech Republic, July 2007.
•	Fahlman, S. E.(2006), "Marker-Passing Inference in the Scone Knowledge-Base System", First International Conference on Knowledge Science, Engineering and Management (KSEM'06), Guilin, China, August 2006.  Proceedings published by and copyright by Springer-Verlag (Lecture Notes in AI).
•	Tribble, A., B. Lambert, and S.E. Fahlman (2006), "SconeEdit: a Text-Guided Domain Knowledge Editor", (demo) HLT-NAACL 2006 Conference, New York, June 2006.
•	Tribble, A. and S. E. Fahlman (2006), "Resolving Noun Compounds with Multi-Use Domain Knowledge", FLAIRS 2006 conference, Melbourne Beach FL, May 2006.
•	Fahlman, S. E. (2002), “Selling interrupt rights: a way to control unwanted E-mail and telephone calls”, IBM Systems Journal, Volume 41, Number 4, 2002, pages 759-766, November 2002.
•	Fahlman, S. E., G. L. Steele Jr., H. Shrobe, B. Stroustrup, and C. A. Knoblock (1996), "The Future of Lisp" in IEEE Expert, vol. 11, no. 1, pp. 10-16, Feb. 1996.
•	Taylor, D.L., L.D. Harris, R.  DeBiasio, S.E.  Fahlman, D.L.  Farkas, F. Lanni, M. Nederlof and A.H. Gough (1996), "Automated Interactive Microscopy: Measuring and Manipulating the Chemical and Molecular Dynamics of Cells and Tissues", in Proceedings of the Conference on Functional Imaging and Optical Manipulation of Living Cells, SPIE Proc. v.2678.
•	Baluja, S. and S. E. Fahlman (1994), "Reducing Network Depth in the Cascade-Correlation Learning Architecture", Tech Report CMU-CS-94-209, School of Computer Science, Carnegie Mellon University.
•	Wah, B. W., S. E. Fahlman, and 22 co-authors (1993), "Report on Workshop on High Performance Computing and Communications for Grand Challenge Applications: Computer Vision, Speech and Natural Language Processing, and Artificial Intelligence" in IEEE Transactions on Knowledge and Data Engineering, Vol.  5, No. 1, February 1993.
•	Hoehfeld, M.  and S. E. Fahlman (1992) "Probabilistic rounding in neural Network Learning with limited precision" in Neurocomputing 4 (1992) pp. 291-299, Elsevier Science Publishers.
•	Hoehfeld, M. and S. E. Fahlman (1992) "Learning with Limited Numerical Precision Using the Cascade-Correlation Learning Algorithm", in IEEE Transactions on Neural Networks, vol.  3, no. 4, pp. 602-611, July 1992.
•	Fahlman, S.  E.  (1991) "The Recurrent Cascade-Correlation Architecture" in Advances in Neural Information Processing Systems 3, D.  S. Touretzky (ed.), Morgan Kaufmann, Los Altos CA, pp. 190-196.
•	Fahlman, S. E. and D. B. McDonald (1990) "Design Considerations for CMU Common Lisp" by Scott E. Fahlman and David B. McDonald, in Peter Lee (ed.)  Advanced Language Implementation Techniques, Springer-Verlag.
•	Fahlman, S.  E. and C. Lebiere (1990) "The Cascade-Correlation Learning Architecture" in Advances in Neural Information Processing Systems 2, D. S.  Touretzky (ed.), Morgan-Kaufmann, Los Altos CA, 1990, pp.  524-532. Reprinted in Artificial Neural Networks: Concepts and Theory, P. Mehra and B. W. Wah (eds.), IEEE Computer Society Press, 1992.
•	Fahlman, S.  E.  (1990) "What Can Massively Parallel Architectures Bring to AI?" Proceedings of 2nd Australian Joint Artificial Intelligence Conference, C.  J.  Barter and M. J. Brooks (eds.), Springer Verlag (Lecture Notes in AI Series).
•	Fahlman, S. E. (1989) "Distributed Connectionist Systems for AI: Prospects and Problems" by Scott E. Fahlman, in Concepts and Characteristics of Knowledge-Based Systems, M.  Tokoro, Y. Anzai, and A.Yonezawa (eds.), North-Holland Publishers.
•	Fahlman, S.  E.  (1988) "Faster-Learning Variations on Back-Propagation: An Empirical Study" in Proceedings, 1988 Connectionist Models Summer School, Morgan-Kaufmann, Los Altos CA.
•	Fahlman, S.  E.  (1987) "Common Lisp" in Annual Review of Computer Science, Volume 2, 1987, Annual Reviews, Inc., Palo Alto, CA.
•	Fahlman, S.  E.  and G.  E.  Hinton (1987) "Connectionist Architectures  for Artificial Intelligence" in IEEE Computer, Vol. 20, number 1, January, 1987.  Reprinted in Computers for Artificial Intelligence Processing B.  W.  Wah and C. V.  Ramamoorthy (eds.), Wiley-Interscience, 1990.  Also reprinted in Knowledge-Based Systems: Fundamentals and Tools, O. N. Garcia and Y. T.  Chien (eds.), IEEE Computer Society Press, 1991).
•	Fahlman, S.  E.  (1988) "Parallel Processing in Artificial Intelligence" (full paper) in "Parallel Computation and Computers for Artificial Intelligence", J. S. Kowalik (editor), Kluwer Academic Publishers.
•	Fahlman, S.  E.  (1985) "Parallel Processing in Artificial Intelligence" (extended abstract) in Parallel Processing 2, North-Holland Publishers.
•	Wholey, J.  S.  and S.  E.  Fahlman (1984) "Design of an Instruction Set for Common Lisp" in Proceedings of 1984 ACM Conference on Lisp and Applicative Programming, Austin, Texas.
•	Major contributor to Steele, G. L. Jr. (1984) Common Lisp: The Language, Digital Press.
•	Fahlman, S. E. and S. P. Harbison (1984) "The Spice Project" in Interactive Programming Environments, Barstow, Sandewall, and Shrobe (eds.), McGraw-Hill, 1984.
•	Fahlman, S.  E., G.  E.  Hinton, and T. J. Sejnowski (1983) "Massively Parallel Architectures for AI: NETL, Thistle, and Boltzmann Machines" in Proceedings of the AAAI-83 Conference, Morgan-Kaufmann, Los Altos CA. Reprinted in Computers for AI Applications, B. Wah and G. J. Li (eds.), IEEE Computer Society Press, 1986.
•	Fahlman, S.  E.  (1982) "Three Flavors of Parallelism", Proceedings of the Fourth National Conference, Canadian Society for Studies of Intelligence, Saskatoon, Saskatchewan.
•	Fahlman, S.  E., D.  S.  Touretzky, and W. van Roggen (1981)  "Cancellation in a Parallel Semantic Network" Proceedings of IJCAI-81, Vancouver, British Columbia.
•	Fahlman, S. E. (1981) "Computing Facilities for AI: A Survey of Present and Near-Future Options", AI Magazine, March 1981.  Reprinted in Computers for AI Applications, B. Wah and G. J. Li (eds.), IEEE Computer Society Press, 1986.  Also reprinted in Readings from the AI Magazine, R. Engelmore (ed.), AAAI Press, 1988.
•	Fahlman, S. E.  (1981) "Representing Implicit Knowledge" in Parallel Models of Associative Memory, G.  E.  Hinton and J. A. Anderson (eds.), Erlbaum Associates, Hillsdale NJ.
•	Fahlman, S. E. (1980) "Design Sketch for a Million-Element NETL Machine", Proceedings of AAAI-80 Conference, Morgan-Kaufmann, Los Altos CA. Reprinted in Computers for AI Applications, B. Wah and G. J. Li (eds.), IEEE Computer Society Press, 1986.
•	Fahlman, S. E. (1980) "The Hashnet Interconnection Scheme", Technical Report, CMU Computer Science Department.
•	Fahlman, S. E. (1979) NETL: A System for Representing and Using Real-World Knowledge, MIT Press, Cambridge MA.
•	Fahlman, S. E. (1974) "A Planning System for Robot Construction Tasks", Artificial Intelligence 5 (1974), 1-49.  Reprinted in Tutorial on Robotics, 2nd Edition, C.  S.  G.  Lee, R. C. Gonzalez, and K. S.  Fu (eds.), IEEE Computer Society Press, 1986.

**PATENTS**:
US Patent #5960080, "Method for transforming message containing sensitive information", Scott E. Fahlman, Rahul Sukthankar, Antoine Brusseau.

**PROFESSIONAL ACTIVITIES**:
•	Keynote Speaker on "Scientific and Artistic Creativity", Regional Arts Education Day, Arts Education Collaborative, Pittsburgh, 2014.
•	Member of the Coordinating Committee, World Communications Forum Davos, 2014-2015.
•	Keynote Speaker, World Communications Forum Davos, 2014.
•	Keynote Speaker and Workshop Organizer, IEEE Conference on Web Intelligence/Intelligent Agent Technology 2013.
•	Member of the editorial board for Advances in Cognitive Systems online journal 2012-2013.
•	Associate editor for the journal Neural Computation (1993-1998).
•	Member of the editorial board for the journal Neurocomputing (1996-1998).
•	Member, DARPA Software Research Review Panel (1995).
•	Member of Scientific Panel for Basics of Information Technology, Siemens Corporation Central Research Laboratories, Munich, 1984 - 1987. Consultant for the same laboratory, 1987-1994.
•	Member of the editorial board, AAAI Press (1990-1994).
•	Program co-chair for Algorithms and Architectures, 1993 and 1994 Neural Information Processing Systems Conference.
•	Member of the editorial board of IEEE Computer (1988-1992).
•	Keynote speaker twice at Australian National AI Conference: 1988 (Adelaide) and 1992 (Hobart).
•	Workshop leader at 1989, 1990, 1991, 1992 NIPS conferences.
•	Invited participant, NSF Workshop on Grand Challenges in AI (Washington DC, 1992).
•	Keynote speaker at 53rd Annual Conference of the Association of Business Professors (Linz, Austria, 1991).
•	Invited panelist, Japanese Science Foundation, Science and Technology Forum '90 (Tsukuba, Japan, 1990).
•	Keynote speaker at 4th IEEE Conference on AI Applications (San Diego, 1988).
•	Invited speaker, British Computer Society (London, 1988).
•	Member of X3J13 committee for the official standardization of Common Lisp, 1986 - 1988.
•	Lecturer at 1986 and 1988 Connectionist Models Summer School.
•	Invited participant/speaker, IFIP Workshop on Concepts and Characteristics of Knowledge-Based Systems (Gotemba, Japan, 1987).
•	Consultant (formerly) for Justsystem Corporation, Fostin Capital Associates, Digital Equipment Corporation, Lucid Inc, Data General, Xerox, IBM, Perq Systems, Expert Technologies Inc., Control Data Corporation, Carnegie Group, Texas Instruments, Topologix, Cable Howse & Cozadd, Warburg-Pincus Ventures.
•	Frequent reviewer for NSF funding proposals, major AI journals and conferences.
•	Member of the Association for Computing Machinery and the Association for  the Advancement of Artificial Intelligence (AAAI).
